[[endpoints]]
listen = "127.0.0.1:10000"
remote = "127.0.0.1:20000"
remote_transport = "ws;host=example.com;path=/chat;tls;sni=example.com;insecure"

[[endpoints]]
listen = "127.0.0.1:20000"
remote = "127.0.0.1:30000"
listen_transport = "ws;host=example.com;path=/chat;tls;servername=example.com"
